version: "3.5"
services:
  pulseaudio:
    build:
      context: ./pulseaudio-server
    devices: 
      - "/dev/snd:/dev/snd"
    expose: 
      - "4713"
    volumes: 
      - "/var/run/dbus:/var/run/dbus"
    privileged: true
  wxwork:
    build:
      context: ./wine/WXWork
    depends_on:
      - pulseaudio
    environment:
      - DISPLAY=unix$DISPLAY
      - GDK_SCALE
      - GDK_DPI_SCALE
      - PULSE_SERVER=tcp:pulseaudio:4713
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:ro"
      - "$HOME/Documents/WXWork:/root"
    shm_size: 2g
